services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - type: bind
        source: ${SSH_AUTH_SOCK}
        target: /ssh-agent
    environment:
      SSH_AUTH_SOCK: /ssh-agent

    command: sleep infinity

    ports:
      - 3000:3000
      - 5000:5000

    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 1212:1212
    command: -p 1212
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  postgres-data:
